echo "Usage: mutihawker [OPTION]..."
echo "Run multihawker script in your directory."
echo "Or specific Bash scripts."
echo ""
echo "-p    Project folder where multihawker.js file is already created"
echo "-t    Execute one of multihawker Bash scripts"
echo "      Usage: -t [taskname] [OPTIONS]"
echo "-s    Execute inline node script"
echo "      Usage: -s [script] [OPTIONS]"
echo "      Example: /path/to/multihawker/multihawker.sh -s \"landing.create('./src','pagename')\""